"""empty message

Revision ID: 32babcd5955a
Revises: 291a976f334e
Create Date: 2018-04-24 11:42:44.409000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32babcd5955a'
down_revision = '291a976f334e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_text', sa.Text(), nullable=True))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', mysql.TEXT(), nullable=True))
    op.drop_column('comment', 'comment_text')
    # ### end Alembic commands ###
