"""empty message

Revision ID: 9ca05030c85c
Revises: 32babcd5955a
Create Date: 2018-04-24 11:56:49.041000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ca05030c85c'
down_revision = '32babcd5955a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'comment_ibfk_2', 'comment', type_='foreignkey')
    op.drop_constraint(u'comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'in_movies', ['movie_id'], ['id'])
    op.drop_column('comment', 'movie')
    op.drop_column('comment', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('movie', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(u'comment_ibfk_1', 'comment', 'user', ['user'], ['id'])
    op.create_foreign_key(u'comment_ibfk_2', 'comment', 'in_movies', ['movie'], ['id'])
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'movie_id')
    # ### end Alembic commands ###
