"""empty message

Revision ID: a8585322feca
Revises: 
Create Date: 2018-04-22 20:22:10.104000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8585322feca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'location')
    op.drop_column('user', 'realname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realname', mysql.VARCHAR(length=125), nullable=True))
    op.add_column('user', sa.Column('location', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('about_me', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
